version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - .:/interview
    ports:
      - '5432:5432'

  app:
    image: interview
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules


# service:
#   pg:
#     image: postgres
#     enviornment:
#       # POSTGRES_USER: postgres
#       # POSTGRES_PASSWORD: postgres
#       # POSTGRES_DB: interview
#     volumes:
#       ./pgData:/var/lib/postgresql/data
#     ports:
#       - '5432:5432'

#   node:
#     image: interview
#     depends_on:
#       - pg
#     ports:
#       - '4000:4000'
